---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tqm
spec:
  schedule: 0 * * * * # hourly
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          initContainers:
            - &container
              name: retag
              image: ghcr.io/home-operations/tqm:1.19.0@sha256:025ee0c0c8b75f4c7bffa90216eedb494b9884e092a47e9c49824fe63427808c
              args:
                - retag
                - qbt
              resources:
                requests:
                  cpu: 10m
                  memory: 128M
                limits:
                  memory: 128M
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
              volumeMounts:
                - name: scratch
                  mountPath: /.config/tqm
                - name: config
                  mountPath: /.config/tqm/config.yaml
                  subPath: config.yaml
                  readOnly: true
                - name: media
                  mountPath: /data
          containers:
            - <<: *container
              name: clean
              args:
                - clean
                - qbt
            # - <<: *container
            #   name: orphan
            #   args:
            #     - orphan
            #     - qbt
          volumes:
            - name: scratch
              emptyDir: {}
            - name: config
              configMap:
                name: tqm
            - name: media
              persistentVolumeClaim:
                claimName: media
